### ISSUE TITLE
Sponsors unclickable

### ISSUE THREAD

**Issue by kozr** [nwplus/nwplus2020#12]
Problem: Clicking on sponsor will not lead you to the sponsored page.

How to reproduce: yarn run dev and then click on any sponsors

**Comment by kozr** [comment]
It could be fixed by pulling sponsor out of mainsection div in index.vue

**Comment by kozr** [comment]
Will someone who's doing the sponsor css in the near future pull it out?

**Comment by Ciuffi** [comment]
@kozr u should assign people so they notice the ticket!

Also do you know why that would fix it? It seems like the email signup is suffering the same fate

**Comment by Ciuffi** [comment]
Okay I fixed it, from now on we shouldn't use z-index = -1.
