### ISSUE TITLE
Animate Learn More button on scroll over

### ISSUE THREAD

**Issue by Ciuffi** [nwplus/nwplus2020#24]
The learn more button should animate like the subscribe button does, to keep consistency.
![image](https://user-images.githubusercontent.com/26512016/61915725-aaac8200-aefa-11e9-9553-0e2ba0da579d.png)

**Comment by Eric1015** [comment]
I can take this one.
How do you want them to animate?
The subscribe button will only change its border.
Personally, I think reversing the white part and light blue is a good idea.

**Comment by Ciuffi** [comment]
Hmm how hard do you think making our own would be? 

We could also ask design for another button.

What do you think?

**Comment by Eric1015** [comment]
![image](https://user-images.githubusercontent.com/31051640/61920998-8bfbc900-af96-11e9-9079-c7a6cef8d9db.png)

If everyone is satisfied with this Bulma library one, it is just copy and paste.

Even they don't like it, it wouldn't take too much time to make one (I have made one before for myself, so basically just copy paste)

**Comment by Ciuffi** [comment]
Ooo I really like bulma’s Actually. Fits the theme too. Let’s implement that for now and if design doesn’t like it we can change it.

**Comment by Eric1015** [comment]
OK.
