### ISSUE TITLE
Fix text on smaller phones (such as iphone 5e)

### ISSUE THREAD

**Issue by Ciuffi** [nwplus/nwplus2020#25]
Some phones are still experiencing text leaking off the screen :/ Here are some samples from Rebecca's 5e:
![image](https://user-images.githubusercontent.com/26512016/61915774-d7f93000-aefa-11e9-9e8c-75d96d4026f1.png)
![image](https://user-images.githubusercontent.com/26512016/61915785-e21b2e80-aefa-11e9-9558-856e06200c7a.png)

**Comment by ianmah** [comment]
going to give it a shot tonight

**Comment by ianmah** [comment]
nvm lol

**Comment by ianmah** [comment]
Tested on my dad's iPhone 5 and it doesn't seem to be working properly. Still cut off.
In Chrome devtools it doesn't look fixed either, however unticking the ```width: 95%``` of .outro p and ticking it again causes weird behaviour: the page refreshes and the margins are fixed but fonts disappear.

**Comment by Ciuffi** [comment]
yeah my fixes didn't end up working :( It looks fine on firefox dev tools. Feel free to give it a try whenever you have the time, I can't seem to get it.

**Comment by Ciuffi** [comment]
https://github.com/nwplus/nwplus2020/commit/f898a1d398dc51bc4e5c2c7b12e416e2e2623840 Might solve this, could someone try it out? @ianmah

**Comment by Ciuffi** [comment]
it works woo
