### ISSUE TITLE
When clicking the navbar anchor link, the navbar hides the header of that section

### ISSUE THREAD

**Issue by Eric1015** [nwplus/nwplus2020#27]
![image](https://user-images.githubusercontent.com/31051640/62000457-84f9c580-b112-11e9-8cfe-d5f4fb05261b.png)

In this case, "Events" is hidden under the navbar.

**Comment by Ciuffi** [comment]
fixed by https://github.com/nwplus/nwplus2020/commit/24f66ee23222bf78fff592deaa6d390d851f3696
