### ISSUE TITLE
Add mailto: link for hello@nwplus.io

### ISSUE THREAD

**Issue by luceliu** [nwplus/nwplus2020#29]
And add link css

**Comment by luceliu** [comment]
@Ciuffi currently the email is just part of some text that's stored in a firebase entry. Is there a way to manipulate the styling without taking it out of firebase and hardcoding it in Outro.vue?

**Comment by Ciuffi** [comment]
That's a good question. 

Do you think the outro is necessary in the CMS? It doesn't seem like something that will be very variable.

**Comment by luceliu** [comment]
I agree aight it's gonna get yeet'd from there

**Comment by Ciuffi** [comment]
closed by #39
