### ISSUE TITLE
background redesign

### ISSUE THREAD

**Issue by Ciuffi** [nwplus/nwplus2020#34]
- [ ] Update background vectors
<img width="499" alt="image" src="https://user-images.githubusercontent.com/26512016/62430228-8c027400-b6ce-11e9-8ba6-5125d2d8a8a9.png">

- [x] update footer colours

<img width="509" alt="image" src="https://user-images.githubusercontent.com/26512016/62430242-bb18e580-b6ce-11e9-8fdf-1011b556c09b.png">

- [x] switch to new bottom background (its now one vector)

<img width="338" alt="image" src="https://user-images.githubusercontent.com/26512016/62430263-121eba80-b6cf-11e9-954e-b282a3263a76.png">

**Comment by ianmah** [comment]
I updated the background and footer colours
The bottom background has been fixed (but i left them as two parts because mobile doesnt include the river graphic)

**Comment by Ciuffi** [comment]
Awesome, thanks @ianmah !
